
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "id numComando : id '=' ExpComando : idExp : Exp '+' TermoExp : Exp '-' TermoExp : TermoTermo : Termo '*' FatorTermo : Termo '/' FatorTermo : FatorFator : '(' Exp ')'Fator : numFator : id"
    
_lr_action_items = {'id':([0,3,8,10,11,12,13,],[2,4,4,4,4,4,4,]),'$end':([1,2,4,5,6,7,9,15,16,17,18,19,],[0,-2,-11,-1,-5,-8,-10,-3,-4,-6,-7,-9,]),'=':([2,],[3,]),'(':([3,8,10,11,12,13,],[8,8,8,8,8,8,]),'num':([3,8,10,11,12,13,],[9,9,9,9,9,9,]),'*':([4,6,7,9,15,16,17,18,19,],[-11,12,-8,-10,12,12,-6,-7,-9,]),'/':([4,6,7,9,15,16,17,18,19,],[-11,13,-8,-10,13,13,-6,-7,-9,]),'+':([4,5,6,7,9,14,15,16,17,18,19,],[-11,10,-5,-8,-10,10,-3,-4,-6,-7,-9,]),'-':([4,5,6,7,9,14,15,16,17,18,19,],[-11,11,-5,-8,-10,11,-3,-4,-6,-7,-9,]),')':([4,6,7,9,14,15,16,17,18,19,],[-11,-5,-8,-10,19,-3,-4,-6,-7,-9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Comando':([0,],[1,]),'Exp':([3,8,],[5,14,]),'Termo':([3,8,10,11,],[6,6,15,16,]),'Fator':([3,8,10,11,12,13,],[7,7,7,7,17,18,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Comando","S'",1,None,None,None),
  ('Comando -> id = Exp','Comando',3,'p_Comando_atribuir','comp_yacc.py',10),
  ('Comando -> id','Comando',1,'p_Comando_atribuir_vazio','comp_yacc.py',14),
  ('Exp -> Exp + Termo','Exp',3,'p_Exp_add','comp_yacc.py',18),
  ('Exp -> Exp - Termo','Exp',3,'p_Exp_sub','comp_yacc.py',22),
  ('Exp -> Termo','Exp',1,'p_Exp_termo','comp_yacc.py',26),
  ('Termo -> Termo * Fator','Termo',3,'p_Termo_mult','comp_yacc.py',30),
  ('Termo -> Termo / Fator','Termo',3,'p_Termo_div','comp_yacc.py',34),
  ('Termo -> Fator','Termo',1,'p_Termo_fator','comp_yacc.py',42),
  ('Fator -> ( Exp )','Fator',3,'p_Fator_par','comp_yacc.py',46),
  ('Fator -> num','Fator',1,'p_Fator_num','comp_yacc.py',50),
  ('Fator -> id','Fator',1,'p_Fator_id','comp_yacc.py',54),
]
